users/urls.py
from django.urls import path

from .views import register,home,login_view,edit_profile,profile_view,logout_view

app_name = 'users'

urlpatterns = [
    path('',home,name='home'),
    path('register/',register,name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout_view'),
    path('edit/<int:user_id>', edit_profile, name='edit_profile'),
    path('profile/<int:user_id>', profile_view, name='profile'),

]

video/urls.py
from django.urls import path

from .views import real_video,detail_video,like,subs,upload_video,my_videos,delete_video,update_video,my_subs_video

app_name = 'video'

urlpatterns = [
    path('',real_video,name='videos'),
    path('detail/<int:my_id>',detail_video,name='detail_video'),
    path('like/<int:pk>',like,name='likes'),
    path('subs/<int:pk>',subs,name='subs'),
    path('upload', upload_video, name='upload_video'),
    path('my_videos', my_videos, name='my_videos'),
    path('delete/<int:video_id>', delete_video, name='delete'),
    path('update/<int:pk>', update_video.as_view(), name='update'),
    path('my_subs_video/', my_subs_video, name='my_subs_video'),

]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('video.urls')),


    path('password_change/',views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_change/', views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),
    path('password_change/', views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'),
         name='password_reset_form'),
    path('password_change/', views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_change/', views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/', views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

video/models.py
from django.db import models

from users.models import User

class Video(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100,)
    desc = models.TextField()
    file = models.FileField(upload_to='videos')
    pub_date = models.DateField(auto_now_add=True)
    views = models.IntegerField(default=0)
    likes = models.ManyToManyField(User,related_name='likes',blank=True)

    def __str__(self):
        return self.title

    def count_like(self):
        return self.likes.count()


class Subscriber(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    subscribers = models.ManyToManyField(User,related_name='subscribers')
    pub_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username




class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Video,on_delete=models.CASCADE,related_name='comments')
    text = models.TextField()
    pub_date = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('pub_date',)

video/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

video/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import UpdateView

from .models import Video,Comment,Subscriber
from users.models import User
from .forms import CommentForm

def real_video(request):

    try:
        videos = Video.objects.all()
    except:
         HttpResponse('dont find')



    context = {
        'videos':videos,
    }

    return render(request,'video/new_release_video.html',context)


def detail_video(request,my_id):
    video = get_object_or_404(Video,pk=my_id)

    count_likes = video.count_like()

    new_comment = None
    comments = video.comments.all()
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.video = video
            new_comment.user = request.user
            new_comment.save()
        else:
            form = CommentForm()
    else:
        form = CommentForm()


    ip = request.META.get('REMOTE_ADDR')
    ips = request.session.get('viewed_ips',[])
    if ip not in ips:
        video.views += 1
        video.save()
        ips.append(ip)
    request.session['viewed_ips'] = ips


    is_self = True
    is_like = False

    if not request.user.is_authenticated or request.user != video.user:
        is_self = False

    if video.likes.filter(pk=request.user.id):
        is_like = True


    dic = {
        'video':video,
        'is_self':is_self,
        'is_like':is_like,
        'count_like':count_likes,
        'comment':comments,
        'comment_form':form,
        'new_comment':new_comment,

    }

    return render(request,'video/detail_video.html',dic)




def like(request,pk):
    is_liked = False
    video = get_object_or_404(Video,id = request.POST.get('video_id'))

    if video.likes.filter(id=request.user.id):
        video.likes.remove(request.user)
        is_liked = False
    else:
        video.likes.add(request.user)
        is_liked = True

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def subs(request,pk):
        is_subs = False
        subscriber = get_object_or_404(Subscriber,user = User.objects.get(id=pk))

        if subscriber.subscribers.filter(id=request.user.id):
            subscriber.subscribers.remove(request.user)
            is_subs = False
        else:
            subscriber.subscribers.add(request.user)
            is_subs = True

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



def upload_video(request):
    if request.POST:
        title = request.POST['title']
        desc = request.POST['desc']
        file = request.FILES['fileName']
        user = request.user
        video = Video(user=user,title=title,desc=desc,file=file)
        video.save()

        return redirect('video:videos')
    return render(request,'video/upload_video.html')



def my_videos(request):

    my_video = Video.objects.filter(user=request.user).order_by('pub_date')

    dic = {
        'my_video':my_video,
    }

    return render(request,'video/my_videos.html',dic)



def delete_video(request,video_id):
    video = get_object_or_404(Video,id=video_id)

    if request.POST:
        video.delete()

    return HttpResponseRedirect(reverse('video:videos'))


class update_video(UpdateView):
    model = Video
    template_name = 'video/edit-video.html'
    fields = ('title','desc')

    def get_success_url(self):
        return reverse('video:my_videos')



def my_subs_video(request):
    subscribers = Subscriber.objects.filter(subscribers = request.user)

    list = []
    for item in subscribers:
        list.append(item.user.id)



    videos = Video.objects.filter(user__id__in=list)

    dic = {
        'my_subs_videos':videos
    }

    return render(request,'video/my_subscribers.html',dic)

templates/video/detail_video.html
{% extends 'base.html' %}

{% block content %}

<h1>VIDEO</h1>
<br><br><br>

        <div class="page-content page-container" id="page-content">
            <div class="padding">
                <div class="row container d-flex justify-content-center">
                    <div class="col-xl-6 col-md-12">
                        <div class="card user-card-full">
                            <div class="row m-l-0 m-r-0">
                                <div class="col-sm-4 bg-c-lite-green user-profile">
                                    <div class="card-block text-center text-white">
                                        <div class="m-b-25"> <img src="{{ video.user.avatar.url }}" class="img-radius" alt="User-Profile-Image"> </div>
                                        @ <a class="user_name" href="{% url 'users:profile' user_id=video.user.id %}">{{ video.user.username}}</a>
                                         <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                    </div>
                                </div>
                                <div class="col-sm-8">
                                    <div class="card-block">
                                        <h6 class="m-b-20 p-b-5 b-b-default f-w-600">
                                            <a href="{% url 'video:detail_video' my_id=video.id %}">{{ video.title }}</a>
                                        </h6>
                                        <div class="row">
            
                                            <video width="270" controls>
                                                <source src="{{ video.file.url }}" type="video/mp4">
                                            </video>
                                        </div>
                                        <br>
                                        <div>
                                            
                                          <form action="{% url 'video:likes' pk=video.pk %}" method="POST">
                                              {% csrf_token %}
                                              {% if user.is_authenticated %}
                                               {% if is_self == False %}

                                                {% if is_like %}
                                                    <button type="submit" name="video_id" value="{{ video.id }}" class="btn btn-secondary">Unlike</button>
                                                {% else %}
                                                <button type="submit" name="video_id" value="{{ video.id }}" class="btn btn-success">Like</button>
                                                {% endif %}
                                                {% endif %}

                                              {% else %}
                                              <h6 style="color: red;">you must be logged in to like this video</h6>
                                              {% endif %}
                                          </form>  
                                        </div>
                                        <ul class="ul_info list-unstyled m-t-40 m-b-10">
                                            <li>views : {{ video.views }}</li>
                                            <li>Likes : {{ count_like }} </li>
                                            <li>Date : {{ video.pub_date }} </li><br>
                                            {% if user.is_authenticated %}
                                               {% if is_self %}

                                            <form action="{% url 'video:delete' video_id=video.pk %}" method="POST">
                                                {% csrf_token %}
                                                <input class="btn btn-outline-danger" type="submit" value="Delete">
                                            </form>
                                               {% endif %}
                                            {% endif %}
                                            
                                        </li><br>
                                            {% if user.is_authenticated %}
                                               {% if is_self %}

                                        <li><a class="btn btn-outline-info" href="{% url 'video:update' pk=video.pk %}">Edit</a></li>
                                               {% endif %}
                                            {% endif %}

                                           <div>
                                               {% for item in comment %}
                                                 {{ item.user.username }}:<br>
                                                 {{ item.text }}<br><br>
                                               -----------------------------------<br>
                                               {% endfor %}

                                               {% if new_comment %}
                                                کامنت ارسال شد

                                               {% endif %}

                                               <form method="post">
                                                 {% csrf_token %}
                                                   {{ comment_form.as_p }}

                                                   <button type="submit" value="ثبت" ></button>
                                               </form>
                                           </div>

                                            

                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        
<style>

    body {
        background-color: #f9f9fa
    }
    
    .padding {
        padding: 3rem !important
    }
    
    .user-card-full {
        overflow: hidden
    }
    
    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        border: none;
        margin-bottom: 10px
    }
    
    .m-r-0 {
        margin-right: 0px
    }
    
    .m-l-0 {
        margin-left: 0px
    }
    
    .user-card-full .user-profile {
        border-radius: 5px 0 0 5px
    }
    
    .bg-c-lite-green {
        background: -webkit-gradient(linear, left top, right top, from(#f29263), to(#ee5a6f));
        background: linear-gradient(to right, #ee5a6f, #f29263)
    }
    
    .user-profile {
        padding: 20px 0
    }
    
    .card-block {
        padding: 1.25rem
    }
    
    .m-b-25 {
    
        margin-bottom: 25px
    }
    .m-b-25 img{
        width: 120px;
        height: 120px;
    }
    
    .img-radius {
        border-radius: 100px
    }
    
    h6 {
        font-size: 14px
    }
    
    .card .card-block p {
        line-height: 25px
    }
    
    @media only screen and (min-width: 1400px) {
        p {
            font-size: 14px
        }
    }
    
    .card-block {
        padding: 1.25rem
    }
    
    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }
    
    .m-b-20 {
        margin-bottom: 20px
    }
    
    .p-b-5 {
        padding-bottom: 5px !important
    }
    
    .card .card-block p {
        line-height: 25px
    }
    
    .m-b-10 {
        margin-bottom: 10px
    }
    
    .text-muted {
        color: #919aa3 !important
    }
    
    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }
    
    .f-w-600 {
        font-weight: 600
    }
    
    .m-b-20 {
        margin-bottom: 20px
    }
    
    .m-t-40 {
        margin-top: 100px
    }
    
    .p-b-5 {
        padding-bottom: 5px !important
    }
    
    .m-b-10 {
        margin-bottom: 10px
    }
    
    .m-t-40 {
        margin-top: 20px
    }
    
    .user-card-full .social-link li {
        display: inline-block
    }
    
    .user-card-full .social-link li a {
        font-size: 20px;
        margin: 0 10px 0 0;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out
    }
    </style>
{% endblock %}

templates/video/edit-video.html
{% extends 'base.html' %}


{% block content %}


<div class="content">
  <div class="border_div">
    <div class="box_form">
      <div class="header_form">
        <h1>Edit Video</h1>
      </div>
      <div class="form_body">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <button>Edit</button>
          </form>
      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/video/my_subscribers.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>NEW VIDEO</h1>
<br><br><br>
    {% for item in my_subs_videos %}


        <div class="page-content page-container" id="page-content">
            <div class="padding">
                <div class="row container d-flex justify-content-center">
                    <div class="col-xl-6 col-md-12">
                        <div class="card user-card-full">
                            <div class="row m-l-0 m-r-0">
                                <div class="col-sm-4 bg-c-lite-green user-profile">
                                    <div class="card-block text-center text-white">
                                        <div class="m-b-25"> <img src="{{ item.user.avatar.url }}" class="img-radius" alt="User-Profile-Image"> </div>
                                        @ <a class="user_name" href="{% url 'users:profile' user_id=item.user.id  %}">{{ item.user.username}}</a>
                                         <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                    </div>
                                </div>
                                <div class="col-sm-8">
                                    <div class="card-block">
                                        <h6 class="m-b-20 p-b-5 b-b-default f-w-600">
                                            <a href="{% url 'video:detail_video' my_id=item.id %}">{{ item.title }}</a>
                                        </h6>
                                        <div class="row">
            
                                            
                                                                               
                                            
                                            <div class="video_box" >
                                                <a href="{% url 'video:detail_video' my_id=item.id %}">
                                                    
                                                    <video width="300"
                                                    onmouseenter='VideoController(true, this)'
                                                    onmouseleave='VideoController(false, this)'
                                                    src="{{ item.avatar.url }}" loop>
                                                </video>
                                                
                                                </a>
                                            </div>
                                        
                                        </div>
                                        <br>
                                        <div>
                                        </div>
                                        <ul class="ul_info list-unstyled m-t-40 m-b-10">
                                            <li>views : {{ item.views }}</li>
                                            <li>Likes : {{ item.likes.count }} </li>
                                            <li>Date : {{ video.pup_date }} </li>

                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>






    {% endfor %}
    <script>
        const VideoController = function(isHovering, videoElement)
{
	if (isHovering == true)
    {
        videoElement.play();
    }
    else if (isHovering == false)
    {
        videoElement.pause();
    }
}
    </script>
<style>

    body {
        background-color: #f9f9fa
    }
    
    .padding {
        padding: 3rem !important
    }
    
    .user-card-full {
        overflow: hidden
    }
    
    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        border: none;
        margin-bottom: 10px
    }
    
    .m-r-0 {
        margin-right: 0px
    }
    
    .m-l-0 {
        margin-left: 0px
    }
    
    .user-card-full .user-profile {
        border-radius: 5px 0 0 5px
    }
    
    .bg-c-lite-green {
        background: -webkit-gradient(linear, left top, right top, from(#f29263), to(#ee5a6f));
        background: linear-gradient(to right, #ee5a6f, #f29263)
    }
    
    .user-profile {
        padding: 20px 0
    }
    
    .card-block {
        padding: 1.25rem
    }
    
    .m-b-25 {
    
        margin-bottom: 25px
    }
    .m-b-25 img{
        width: 120px;
        height: 120px;
    }
    
    .img-radius {
        border-radius: 100px
    }
    
    h6 {
        font-size: 14px
    }
    
    .card .card-block p {
        line-height: 25px
    }
    
    @media only screen and (min-width: 1400px) {
        p {
            font-size: 14px
        }
    }
    
    .card-block {
        padding: 1.25rem
    }
    
    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }
    
    .m-b-20 {
        margin-bottom: 20px
    }
    
    .p-b-5 {
        padding-bottom: 5px !important
    }
    
    .card .card-block p {
        line-height: 25px
    }
    
    .m-b-10 {
        margin-bottom: 10px
    }
    
    .text-muted {
        color: #919aa3 !important
    }
    
    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }
    
    .f-w-600 {
        font-weight: 600
    }
    
    .m-b-20 {
        margin-bottom: 20px
    }
    
    .m-t-40 {
        margin-top: 100px
    }
    
    .p-b-5 {
        padding-bottom: 5px !important
    }
    
    .m-b-10 {
        margin-bottom: 10px
    }
    
    .m-t-40 {
        margin-top: 20px
    }
    
    .user-card-full .social-link li {
        display: inline-block
    }
    
    .user-card-full .social-link li a {
        font-size: 20px;
        margin: 0 10px 0 0;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out
    }
    </style>
    

        
{% endblock %}

templates/video/my_videos.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>NEW VIDEO</h1>
<br><br><br>
    {% for item in my_video %}


        <div class="page-content page-container" id="page-content">
            <div class="padding">
                <div class="row container d-flex justify-content-center">
                    <div class="col-xl-6 col-md-12">
                        <div class="card user-card-full">
                            <div class="row m-l-0 m-r-0">
                                <div class="col-sm-4 bg-c-lite-green user-profile">
                                    <div class="card-block text-center text-white">
                                        <div class="m-b-25"> <img src="{{ item.user.avatar.url }}" class="img-radius" alt="User-Profile-Image"> </div>
                                        @ <a class="user_name" href="{% url 'users:profile' user_id=item.user.id  %}">{{ item.user.username}}</a>
                                         <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                    </div>
                                </div>
                                <div class="col-sm-8">
                                    <div class="card-block">
                                        <h6 class="m-b-20 p-b-5 b-b-default f-w-600">
                                            <a href="{% url 'video:detail_video' my_id=item.id %}">{{ item.title }}</a>
                                        </h6>
                                        <div class="row">
            
                                            
                                                                               
                                            
                                            <div class="video_box" >
                                                <a href="{% url 'video:detail_video' my_id=item.id %}">
                                                    
                                                    <video width="300"
                                                    onmouseenter='VideoController(true, this)'
                                                    onmouseleave='VideoController(false, this)'
                                                    src="{{ item.file.url }}" loop>
                                                </video>
                                                
                                                </a>
                                            </div>
                                        
                                        </div>
                                        <br>
                                        <div>
                                        </div>
                                        <ul class="ul_info list-unstyled m-t-40 m-b-10">
                                            <li>views : {{ item.views }}</li>
                                            <li>Likes : {{ item.likes.count }} </li>
                                            
                                            <li>Date : {{ video.pup_date }} </li>

                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>






    {% endfor %}
    <script>
        const VideoController = function(isHovering, videoElement)
{
	if (isHovering == true)
    {
        videoElement.play();
    }
    else if (isHovering == false)
    {
        videoElement.pause();
    }
}
    </script>
<style>

    body {
        background-color: #f9f9fa
    }
    
    .padding {
        padding: 3rem !important
    }
    
    .user-card-full {
        overflow: hidden
    }
    
    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        border: none;
        margin-bottom: 10px
    }
    
    .m-r-0 {
        margin-right: 0px
    }
    
    .m-l-0 {
        margin-left: 0px
    }
    
    .user-card-full .user-profile {
        border-radius: 5px 0 0 5px
    }
    
    .bg-c-lite-green {
        background: -webkit-gradient(linear, left top, right top, from(#f29263), to(#ee5a6f));
        background: linear-gradient(to right, #ee5a6f, #f29263)
    }
    
    .user-profile {
        padding: 20px 0
    }
    
    .card-block {
        padding: 1.25rem
    }
    
    .m-b-25 {
    
        margin-bottom: 25px
    }
    .m-b-25 img{
        width: 120px;
        height: 120px;
    }
    
    .img-radius {
        border-radius: 100px
    }
    
    h6 {
        font-size: 14px
    }
    
    .card .card-block p {
        line-height: 25px
    }
    
    @media only screen and (min-width: 1400px) {
        p {
            font-size: 14px
        }
    }
    
    .card-block {
        padding: 1.25rem
    }
    
    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }
    
    .m-b-20 {
        margin-bottom: 20px
    }
    
    .p-b-5 {
        padding-bottom: 5px !important
    }
    
    .card .card-block p {
        line-height: 25px
    }
    
    .m-b-10 {
        margin-bottom: 10px
    }
    
    .text-muted {
        color: #919aa3 !important
    }
    
    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }
    
    .f-w-600 {
        font-weight: 600
    }
    
    .m-b-20 {
        margin-bottom: 20px
    }
    
    .m-t-40 {
        margin-top: 100px
    }
    
    .p-b-5 {
        padding-bottom: 5px !important
    }
    
    .m-b-10 {
        margin-bottom: 10px
    }
    
    .m-t-40 {
        margin-top: 20px
    }
    
    .user-card-full .social-link li {
        display: inline-block
    }
    
    .user-card-full .social-link li a {
        font-size: 20px;
        margin: 0 10px 0 0;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out
    }
    </style>
    

        
{% endblock %}

templates/video/upload_video.html
{% extends 'base.html' %}


{% block content %}

{% if user.is_authenticated %}
<div class="content">
  <div class="border_div">
    <div class="box_form">
      <div class="header_form">
        <h1>Upload Video</h1>
      </div>
      <div class="form_body">

        
        <form action="{% url 'video:upload_video' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label >Title</label>
                <input type="text" name="title" required>
            </div><br>
    
            <div>
                <label >Description</label>
                <textarea name="desc" id="desc" style="height: 200px;" required></textarea>
            </div><br>
    
            <div>
                <label for="filename" >Select Video File</label>
                <input type="file" name="fileName" id="filename" accept="video/*" required>
            </div><br>
        
    
            <button type="submit">Upload</button>
        </form>        
        
        
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}