users/urls.py
from django.urls import path

from .views import register,home,login_view,edit_profile,profile_view,logout_view

app_name = 'users'

urlpatterns = [
    path('',home,name='home'),
    path('register/',register,name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout_view'),
    path('edit/<int:user_id>', edit_profile, name='edit_profile'),
    path('profile/<int:user_id>', profile_view, name='profile'),

]

video/urls.py
from django.urls import path

from .views import real_video,detail_video,like,subs,upload_video,my_videos,delete_video,update_video,my_subs_video

app_name = 'video'

urlpatterns = [
    path('',real_video,name='videos'),
    path('detail/<int:my_id>',detail_video,name='detail_video'),
    path('like/<int:pk>',like,name='likes'),
    path('subs/<int:pk>',subs,name='subs'),
    path('upload', upload_video, name='upload_video'),
    path('my_videos', my_videos, name='my_videos'),
    path('delete/<int:video_id>', delete_video, name='delete'),
    path('update/<int:pk>', update_video.as_view(), name='update'),
    path('my_subs_video/', my_subs_video, name='my_subs_video'),

]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('video.urls')),


    path('password_change/',views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_change/', views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),
    path('password_change/', views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'),
         name='password_reset_form'),
    path('password_change/', views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_change/', views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/', views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script> 
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django videos</title>
</head>
<body>
    <div class="container" >
        {% csrf_token %}
        <!------------------ navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'video:videos' %}">Django Videos</a>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'users:home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'video:my_videos' %}">My videos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'video:my_subs_video' %}">My Subscribers</a>
                </li>
                {% endif %}
                </ul>
            </div>
            </div>


            {% if user.is_authenticated %}
                <div class="btn-group">
                    <div class="img_profile_header" >
                        <img src="{{ user.profile_image.url }}" alt="">
                    </div>
                    <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Hi {{ user.username }}
                    </button>
                    <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'users:profile' user_id=user.id  %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:edit_profile' user_id=user.id %}">Edit Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'video:upload_video' %}">Upload Video</a></li>
                    <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'users:logout_view' %}">Sign out</a></li>
                    </ul>
                </div>

            {% else %}
                <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
            {% endif %}
        </nav>
        
        
    

        
        {% block content %}
        
        {% endblock content %}
    </div>

</body>